### ISSUE TITLE
com.novus.salat.dao.DAO class is missing "findAndModify"

### ISSUE THREAD

**Issue by ysukhoverkhov** [salat/salat#115]
I can fork and add it there and implement in SalatDAO and make a pull request if you like. If by some reason you think it should not be there I'll make it privately.

Thank you :).

**Comment by noahlz** [comment]
I'm going through old issues, and I must say that this seems like a reasonable request!

**Comment by noahlz** [comment]
See PR #1175 targeting `1.10.x-branch`

**Comment by noahlz** [comment]
I implemented this on the 1.10.x branch. #175
