### ISSUE TITLE
Are SalatDAO objects thread safe?

### ISSUE THREAD

**Issue by zon** [salat/salat#122]
Is it safe to use a SalatDAO object like the example in the wiki across multiple threads or should we be using separate class instances instead?

```scala
object AlphaDAO extends SalatDAO[Alpha, Int](collection = MongoConnection()("test_db")("test_coll"))
```

**Comment by noahlz** [comment]
@zon - first of all, apologies for the belated (perhaps too late) reply.

Salat is essentially stateless, and any concurrency issues would be in Casbah or the mongo-java-driver.

Novus Partners used Salat for years with various DAO implementations being singletons shared across threads, with no problems that I was aware of.

If you (or anybody else reading this Issue) comes across a problem, by all means please open a new Issue or PR!
