### ISSUE TITLE
Map with an array in it

### ISSUE THREAD

**Issue by caente** [salat/salat#128]
Hi, one of the fields in a document has this form:
```
{ "1" : [ ] , "2" : [ ] , "3" : [ ] , "4" : [ ] , "5" : [ ] , "6" : [ ] , "7" : [ ]}
```

those `[]` are actually meant to contain an array of elements like this one:
`{"start": 12121,"end": 12121}`

Which in my scala code is a a case class:
`case class MidnightRange(start: Int,end: Int)`
and the map is declared like this: 
`Map[String, List[MidnightRange]]`

But when trying to retrieve the object I'm getting an error:
```
---------- CONSTRUCTOR EXPECTS FOR PARAM [4] --------------
NAME:          elements
TYPE:	      scala.collection.immutable.Map<java.lang.String, scala.collection.immutable.List<MidnightRange>>
DEFAULT ARG   Map()
@Ignore	      false
---------- CONSTRUCTOR INPUT ------------------------
TYPE: com.mongodb.BasicDBObject
VALUE:
{ "1" : [ ] , "2" : [ ] , "3" : [ ] , "4" : [ ] , "5" : [ ] , "6" : [ ] , "7" : [ ]}
```

The default value is an empty Map, as you can see.

Does this happen because of the empty arrays? Is there any workaround?

**Comment by caente** [comment]
Well, I had the Map as a type = `Map[String, List[MidnightRange]]` inside an object, removed that and stopped getting that error, now I', having `com.mongodb.BasicDBList` cannot be cast to `scala.collection.immutable.List` when trying to access to the content of the Map, it should have returned an empty list

**Comment by noahlz** [comment]
Is your `Map[String, List[MidnightRange]]` a member of another case class, e.g.

```scala
case class Ranges(data: Map[String, List[MidnightRange]])
```
 or are you attempting to use Salat to store and retrieve the map directly?

**Comment by noahlz** [comment]
In Salat `1.9.10` and the forthcoming `1.10.0` release (currently in snapshot) you will see an error message like the following:

```
NOTE: salat has certain limitations. It cannot deserialize JSON into case classes having fields such as:
- Arrays such as Array[String]
- Nested collections such as Map[String, List[String]]
- Optional collections such as Option[List[String]]

For more information, please visit: https://github.com/salat/salat/wiki/SupportedTypes
```

in this case, the problem is that Salat does not currently support Maps that have List values.
