### ISSUE TITLE
Constructor of case classes that extend @Salat annotated traits, misbehave in Future

### ISSUE THREAD

**Issue by shayanlinux** [salat/salat#134]
We use Salat via [Play-Salat](https://github.com/leon/play-salat) in Play Framework 2.3.3. Here is a minimal example of the class hierarchy:
```scala
@Salat
trait BaseEntity {
  val id: ObjectId
}

@Salat
sealed trait Notification {
  val tags: Set[ObjectId]
}

case class MessageNotification(
  actor: ObjectId,
  message: ObjectId,
  tags: Set[ObjectId],
  id: ObjectId = new ObjectId) extends BaseEntity with Notification
```
Now if we construct an instance of that case class in a Future block, the commands after that point are not executed, for example:
```scala
def timeTravel = Action() { implicit request =>
  // this works fine
  val not1 = MessageNotification(new ObjectId, new ObjectId, Set(new ObjectId))
  dao.insert(not1)
  Future {
    println("this will be printed")
    // this does not work
    val not2 = MessageNotification(new ObjectId, new ObjectId, Set(new ObjectId))
    println("this will not be printed")
    // and this won't happen
    dao.insert(not2)
  }
  Ok()
}
```
I try to setup a minimal project to demonstrate this, but let's roll the ball first ;-)
Any clue what might cause this?
Please let me know if you need more info and thanks in advance for looking into this.

**Comment by diagonal-e** [comment]
@shayanlinux, if it's terminating on that line, that implies that there's an uncaught exception. I have no idea what the exception might be, but adding a try/catch would let you at least see what it is.

**Comment by noahlz** [comment]
It is unclear to me how a `Future` not returning due to a mysterious silent deadlock(???) in a vanilla case class constructor is relevant to Salat functionality.

Reactive Mongo support should be a separate issue / request.
