### ISSUE TITLE
Seq[Byte] gets serialised as array of ints

### ISSUE THREAD

**Issue by glorat** [salat/salat#135]
Per other similar issues raised on this topic, Array[Byte] works fine. 

However, case classes are extremely useful as "value objects" whereby equality is recursively based on the contents of the case class, rather than memory references. For that reason, it is very useful to have
case class MyValueObject(seq:Seq[Byte]) 
so that two such instances with identical seq are equal. This will not happen if it is an Array[Byte]

I'd rather not have to maintain separate case classes for my model and my mongo storage so I'd really like Seq[Byte] supported by serializing it to Binary. I'm even willing to help code it up if given a few pointers and suggestion as to whether this is reasonable doable. If this is hard (and I'm guessing it might be due to lack of support so far), also let me know

Thanks,

**Comment by glorat** [comment]
@rktoomey One year on, I'm looking at revisiting this! Did you happen to look into this? Otherwise, I'm getting at the stage where I no longer want to workaround this so would want to support Seq[Byte]->Binary

Per JSON - I have no expectation. Array of ints would seem to make most sense there.

Or if you can point me to the right place in the code, I could try hacking this in myself

**Comment by noahlz** [comment]
Hello @glorat! Thanks for offering to take a crack at this. Between work and family, @rktoomey and I are both pretty slammed these days.

I think you'll find `salat-util/src/main/scala/com/novus/salat/TypeMatchers.scala` to be a good starting point for discovering how Salat identifies the types of case class fields. From there you could trace through its usage of that class and methods.

**Comment by glorat** [comment]
Okay, I'll see if I have both time and competency to figure it out.

Btw, on further thought, for JSON serialization, actually I think Seq[Byte]/Binary are best serialized as Base64, which seems to be the most common way of shipping around blobs from JavaScript

**Comment by noahlz** [comment]
This issue was handled in PR #155 which I ported to `1.10.x` branch in #174. Closing this issue for now as the PR is open and 1.10.0 is imminent.
