### ISSUE TITLE
Grater nested lists deserialization

### ISSUE THREAD

**Issue by lbielski** [salat/salat#136]
import com.novus.salat._
    import com.novus.salat.global._
    import com.mongodb.casbah.Imports._

    case class Ingredient(name: String)
    case class Dish(ingredients: List[List[Ingredient]])

    object Test extends App {   
   
        val test = Dish(List(List(Ingredient("test"))))
   
        val coll: MongoCollection = MongoClient("localhost", 27017)("estes")("test")
        coll.insert(grater[Dish].asDBObject(test))
   
        val result = coll.find().map(dbo => grater[Dish].asObject(dbo)).toList
        println(result)
   
    }

I get `List(Dish(List([ [ "test"]])))` printed

instead of

`List(Dish(List(List( ["test"])))`

Nested list is just `BasicDBList` instead of being properly converted to `List`

**Comment by noahlz** [comment]
I'm closing this old issue. As mentioned, nested lists are not currently supported, we're open to PRs adding such a feature - please target `1.10.x-branch`
