### ISSUE TITLE
Please publish 2.0.0-SNAPSHOT to Sonatype

### ISSUE THREAD

**Issue by luisfurnas** [salat/salat#142]
I've tried to add Salat 2.0.0-Snapshot to my Play 2 app, and I got an unresolved dependency error.
I checked the Sonatype Snapshots repository, and there's no Salat 2.0.0 Snapshot there.

**Comment by ShaneKilkelly** [comment]
I've just run into this too.

**Comment by fredley** [comment]
Year and a half later, still waiting...

**Comment by ShaneKilkelly** [comment]
Project appears to be dead, unfortunately.

**Comment by noahlz** [comment]
Hello all - Salat is not exactly dead...it's more like...in an extended coma induced by Full Time Employment and Natural Learning Intelligence side-projects (a.k.a children).  

I'm going to set aside some time this long weekend to tackle some of these small issues like publishing a 2.0 snapshot and hopefully releasing a 1.x that fixes some small outstanding bugs.  

In the meantime, I recommend you clone the project and `sbt publish-local` to get yourself unblocked.

Thanks!

**Comment by noahlz** [comment]
Arise, salat! 

https://oss.sonatype.org/content/repositories/snapshots/com/github/salat/

Latest snapshots off master published.
