### ISSUE TITLE
Update dependencies to use casbah 2.8

### ISSUE THREAD

**Issue by jeroenr** [salat/salat#145]
Would be great to update the project to use Casbah 2.8, so we can benefit from the Java Mongo Driver (v. 2.13) that officially support Mongo 3. See also http://docs.mongodb.org/ecosystem/drivers/java/

**Comment by sief** [comment]
+1

**Comment by mzafer** [comment]
+1

**Comment by Zi0P4tch0** [comment]
+1 - Is the project dead?

**Comment by noahlz** [comment]
Hello all - I have reached out to @rktoomey for comment on this, so look for her input in the near future.

Regarding the project status - Salat is most definitely not dead, but it is certainly in a period of transition as Rose - our project lead and all-around Salat mastermind - left Novus late last year but is still (and will continue to be) very much in charge of this project. More to come on this in the next few weeks.

**Comment by jeroenr** [comment]
any update on this?

**Comment by danslapman** [comment]
+1

**Comment by noahlz** [comment]
Hey all - don't know if you saw #149 - Salat has been spun off into a stand-alone project and we (well, Rose), is getting some things in order before resuming with major development / 2.0 etc.

In the mean time, if you would like to contribute a PR that upgrades to Casbah 2.8, along with any changes to address compatibility issues, and testing notes, that would be a great help. Thanks!

**Comment by noahlz** [comment]
Hello all - the key commits from #157 are in `1.10.0-SNAPSHOT` which I just published.

As mentioned over in #158 if someone wants to give the snapshot release a while and confirm it's all good, it will give me some confidence to do a stable release of 1.10.0 with Casbah 2.8.2 support.

Thanks, and apologies for the delay!

**Comment by noahlz** [comment]
Hello all - I am closing this as a "Duplicate" of #158 - please hop over there for on-going discussion of adding Casbah 2.8.2 support.
