### ISSUE TITLE
Play Salat

### ISSUE THREAD

**Issue by leon** [salat/salat#159]
Hi!

I'm no longer maintaining play-salat, and I've got a few requests to get play-salat updated to play 2.4

I think it would be a good idea to move play-salat to this organisation and invite a few other contributors.

What do you think?

**Comment by rcaloras** [comment]
:+1:

**Comment by julianpeeters** [comment]
+1 (thanks for the library, Leon!)

**Comment by noahlz** [comment]
Hello @leon - sincere apologies for not responding sooner.

It looks like play-salat was moved to @cloudinsights repository? If so, I'll close this issue.

(Also, we'll have to update the README appropriately)

**Comment by noahlz** [comment]
Hello @leon - sincere apologies for not responding sooner.

It looks like play-salat was moved to @cloudinsights repository? If so, I'll close this issue.

**Comment by noahlz** [comment]
Closing this issue - @cloudinsights feel free to reopen if you would like play-salat to reside here.
