### ISSUE TITLE
SalatDAO support for collections

### ISSUE THREAD

**Issue by pferrel** [salat/salat#197]
I was under the impression that there was no support for objects with collections in them but reading the collection support page now makes me question this assumption. I have many objects that are like this:

```
case class CBGroupInitProperties (
  groupId: String,
  testPeriodStart: String, // ISO8601 date
  variants: Seq[String], //["17","18"]
  testPeriodEnd: Option[String])
```

I have a Casbah `MongoCollection` of these and would like to treat the collection as a DAO of `CBGroupInitProperties` but given the presence of `variants` as a `Seq[String]` is this possible?

**Comment by pferrel** [comment]
Is there a google group or mailing list?

UPDATE: nm, found the group

**Comment by pferrel** [comment]
I think I found the answer, the last time I posted to the group. An object can have a collection, but not a collection that has a collection, like `Map[String, Seq[String]]`. The `Seq[String]` here is the part not allowed. As long as the collection has no objects like this, I'm ok.

**Comment by noahlz** [comment]
Yes, collections are supported just not nested collections or collections as values of Maps.

There is no technical reason for not supporting nested collections. The original authors of Salat left it for another day (that day being several years and counting at this point). 

The group is scala-salat on Google Groups.

**Comment by pferrel** [comment]
I have the following case class that I'm persisting using a SalatDAO.

```
case class GroupParams (
  _id: String,
  testPeriodStart: DateTime, // ISO8601 date
  pageVariants: Map[Int, String], //((1 -> "17"),(2 -> "18"))
  testPeriodEnd: Option[DateTime]) extends CBEvent

```

The pageVariants if created as `Map[Int, String]` and looks like this in Mongo:

```
> db.groups.find().pretty()
{
	"_id" : "1",
	"testPeriodStart" : ISODate("2017-06-01T18:30:00Z"),
	"pageVariants" : {
		"0" : "1",
		"1" : "2"
	},
	"testPeriodEnd" : ISODate("2017-10-09T18:30:00Z")
}
> 
```

When I get the "group" back out:

```
val group = dataset.GroupsDAO.findOneById(query.groupId).get
```

using the `_id` the Map created has correct data but pageVariants is a `Map[String, String]` which breaks  other code. I was expecting the key set for the Map to be Int. What am I doing wrong?

**Comment by pferrel** [comment]
Here is my DAO creation:

```
  object GroupsDAO extends SalatDAO[GroupParams, String](collection = connection(resourceId)("groups"))
```

Obviously the objects stored in the DAO are each correctly typed and I have:

```
import salat.global._
```

in the file, just in case type hinting is needed. My understanding is that this is all I had to do to get hinting but I see no hints in Mongo as you see above.

**Comment by pferrel** [comment]
I guess this boils down to the fact that the first value in `pageVariants` tuples should be deserialized as an Int not a String.

**Comment by noahlz** [comment]
Salat requires that maps have string keys.

https://github.com/salat/salat/wiki/Collections
