### ISSUE TITLE
API improvement suggestion for SalatDAO

### ISSUE THREAD

**Issue by manuelbernhardt** [salat/salat#20]
SalatDAO offers convenient methods such as update, insert, ...

However, unlike casbah, these methods are Units and do not return a `com.mongodb.WriteResult`. So this makes checking whether an object has been written sort of awkward. Would it perhaps be possible to return such a nice WriteResult?

Or is there another way to do the checking that I am not aware of?

**Comment by noahlz** [comment]
(Triaging old issues...)

This appears to be one that slipped through the cracks, as in `1.9.10` and `1.10.0-SNAPSHOT` I see that insert returns `Option[ID]`, update returns a `WriteResult` and remove also returns a `WriteResult`.

So...I'm closing this issue. 

Please comment / re-open / open a new issue if I got this wrong!
