### ISSUE TITLE
Optional field in MongoDBObject with null value causing MatchError

### ISSUE THREAD

**Issue by niwic** [salat/salat#200]
There was a change to the getAs method in casbah 3.1.1 that seems to be causing an issue in salat. The change I'm referring to is this one https://github.com/mongodb/casbah/commit/1077fb7f3ac5883e6e36dfb909c8fd71b95e4a89.

In https://github.com/salat/salat/blob/1.11.x-branch/salat-core/src/main/scala/salat/Grater.scala#L306, getAs is called. The problem arises when there is a field which is in the object, but is null. The changed behavior in casbah returns Some(None), resulting in None being sent to the transformation. This in turn causes a MatchError for None (ex. https://github.com/salat/salat/blob/1.11.x-branch/salat-core/src/main/scala/salat/transformers/inject/Injectors.scala#L389).

The following code results in a MatchError using salat 1.11.0 & casbah 3.1.1:
```scala
import com.mongodb.casbah.commons.MongoDBObject
import com.mongodb.casbah.Imports._
import salat._
import salat.global._

case class Test (test: Option[Char])

object Main extends App {

  val testGrater = grater[Test]
  val testDbObject = MongoDBObject("test" -> null) // A dbobject where the optional value is defined, but null
  val test = testGrater.asObject(testDbObject) // None is passed along to the transformer using casbah 3.1.1
  // This results in a MatchError: None

  print(test)

}
```

```
Exception in thread "main" scala.MatchError: None (of class scala.None$)
	at salat.transformers.in.StringToChar$class.transform(Injectors.scala:389)
	at salat.transformers.in.package$$anon$7.transform(Injectors.scala:58)
	at salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:101)
	at salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:101)
	at scala.Option.flatMap(Option.scala:171)
	at salat.transformers.Transformer.transform_$bang(Transformer.scala:101)
	at salat.Field.in_$bang(Field.scala:73)
	at salat.ConcreteGrater$$anonfun$5$$anonfun$apply$2.apply(Grater.scala:317)
	at salat.ConcreteGrater$$anonfun$5$$anonfun$apply$2.apply(Grater.scala:317)
	at scala.Option.flatMap(Option.scala:171)
	at salat.ConcreteGrater$$anonfun$5.apply(Grater.scala:317)
	at salat.ConcreteGrater$$anonfun$5.apply(Grater.scala:302)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at salat.ConcreteGrater.asObject(Grater.scala:302)
	at Main$.delayedEndpoint$Main$1(Main.scala:12)
	at Main$delayedInit$body.apply(Main.scala:8)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$.main(Main.scala:8)
	at Main.main(Main.scala)
```

Is this a bug or am I doing something incorrectly?

**Comment by noahlz** [comment]
As solution to this is slightly complicated by salat's `Context.suppressDefaultArgs` feature.

If a context has `override val suppressDefaultArgs = true`, then from `Test(test = None)` it will generate JSON like `{}`.  

However, if `suppressDefaultArgs = false` it will generate `{ "test" : null }` which will be parsed into `Test(test = Some(None)`. So a round trip would be broken.

The comments on the commit you linked to seem to imply that the Casbah team recognized the problems this was causing and were going to fix it...

Do we fix this in Salat or recommend that users upgrade to a more recent version of Casbah?  Seems like this is not a Salat-specific issue and is biting any code that relied on the old behavior.

**Comment by niwic** [comment]
I tried using supressDefaultArgs as you suggested. This seems to work if you convert the case class into a DBObject (asDBObject) and then convert it back to the case class again (asObject). The code from my original post still does not seem to work even with the argument set.

This means there still is a chance that is a null value stored in MongoDB, which will cause the MatchError when passed to salat.

I interpret the comments in the commit i linked to as meaning the change is actually a fix for something that did not work as intended earlier. This is further underlined by them removing the "skipped" keyword from an old test. This leads me to believe the behavior will not be changed back in any future version of casbah.

**Comment by noahlz** [comment]
Apologies, I didn't intend `suppressDefaultArgs` to be a proposed work around. Rather, I was observing that - wow - there might not be an elegant solution for this one.  

Salat has historically been very forgiving of Option fields, meaning `null` is parsed as option, i.e. `{ "foo" : null }` is interpreted as `None` - but absence of the field i.e. `{ }` is now also interpreted as `None` (as long as the case class had a default value for the field). As I recall, there was not really a way to represent `Some(None)` or even `Some(null)`.  

I guess what I'm saying is: we're open to suggestions (PRs) on how to handle this!  It could be that the ultimate solution will be backwards incompatible,  and upgrading to Salat 1.11.x / Casbah 3.1+ will require some migrations code changes to handle the new behavior.

**Comment by noahlz** [comment]
Relevant links from the Casbah changelog:

http://mongodb.github.io/casbah/3.1/changelog/

https://jira.mongodb.org/browse/CASBAH-169

**Comment by noahlz** [comment]
Looking at this a little more in a spare moment:

From the changelog 

> If the value is present and null, the method will now return > Some(None), if it is not present, it will return None.

**Comment by noahlz** [comment]
note: #199 appears similar but is unrelated and has to do with JSON parsing.

If someone wants to contribute a proposed fix to this, it would be appreciated. Otherwise, I'll try to have a look in my spare time.

**Comment by noahlz** [comment]
Update: I had a look in my spare time. See PR #206 for the proposed fix.

**Comment by noahlz** [comment]
I've published 1.11.2-SNAPSHOT which includes the fix for this issue.  Versions for 2.10, 2.11 and 2.12.

Note that you have to add the sonatype snapshot repository to access the snapshot.
build.sbt line:

`resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"`

Example successful build log output:

```
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/github/salat/salat-util_2.11/1.11.2-SNAPSHOT/salat-util_2.11-1.11.2-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.github.salat#salat-util_2.11;1.11.2-SNAPSHOT!salat-util_2.11.jar (1852ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/github/salat/salat-core_2.11/1.11.2-SNAPSHOT/salat-core_2.11-1.11.2-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.github.salat#salat-core_2.11;1.11.2-SNAPSHOT!salat-core_2.11.jar (1613ms)
```

Please test and let me know if there any issue, and I'll release a little later this week.

**Comment by niwic** [comment]
I'm seeing an error related to a case class where we have a field defined as Seq[DBObject]. We get an exception when we then treat the field as a Seq[DBObject] (doing object.field.map(_...)). It seems it has been unserialized into a sequence of HashMap and/or HashTrieMap. The exception is: "scala.collection.immutable.HashMap$HashTrieMap cannot be cast to com.mongodb.DBObject".

I need to do some more investigation in order to figure out what the root cause is, but I don't remember seeing this before trying the snapshot version.

All our other integration & end to end tests seem to be passing (after additionally applying a work-around for this casbah issue: https://jira.mongodb.org/browse/CASBAH-201).

**Comment by niwic** [comment]
After fiddling around with this for a while now, I'm pretty sure I was mistaken and the exception is NOT caused by any recent change in salat.

**Comment by noahlz** [comment]
1.11.2 is released and available in Maven Central.
