### ISSUE TITLE
Custom Transformers never get applied to case classes

### ISSUE THREAD

**Issue by noahlz** [salat/salat#203]
See #92 

According to lore / old comments, this issue was approved by @rktoomey and should have been released with 1.9.3...but it seems like it was not?  The existing code in the current release has the old code without the change from #92 applied.

Opening this issue as a placeholder to look into this and resolve it if (likely) necessary.

cc @edmondo1984 @duncancrawford @thiloplanz

**Comment by potmat** [comment]
Been tearing my hair out over this the past day wondering why my transformer wasn't working.  Would be much appreciated.

**Comment by noahlz** [comment]
Ok, what specific Salat version are you using? We have 3 branches (1.9, 1.10, 1.11) and I would prefer to release on 1.11 and only back-port fixes to the other two branches upon request.

**Comment by potmat** [comment]
We're on 1.9 right now, but I'll take a look at upgrading and trying out the branch.

**Comment by potmat** [comment]
Don't seem to have any problems moving from 1.9->1.11 so don't worry about back-porting.

**Comment by noahlz** [comment]
Awesome, thanks!

Regarding Maven versions, I find this site helpful: https://mvnrepository.com/artifact/com.github.salat

(There might be better ones out there, this is the one I use habitually)

**Comment by potmat** [comment]
Re: Maven versions

I use the same site, the problem I had was that I was looking under the old com.novus group.

[https://search.maven.org/](https://search.maven.org/) set me straight (so I sheepishly edited my comment)

**Comment by noahlz** [comment]
I've published 1.11.2-SNAPSHOT which includes the fix for this issue.  Versions for 2.10, 2.11 and 2.12.

Note that you have to add the sonatype snapshot repository to access the snapshot.
build.sbt line:

`resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"`

Example successful build log output:

```
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/github/salat/salat-util_2.11/1.11.2-SNAPSHOT/salat-util_2.11-1.11.2-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.github.salat#salat-util_2.11;1.11.2-SNAPSHOT!salat-util_2.11.jar (1852ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/github/salat/salat-core_2.11/1.11.2-SNAPSHOT/salat-core_2.11-1.11.2-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.github.salat#salat-core_2.11;1.11.2-SNAPSHOT!salat-core_2.11.jar (1613ms)
```

Please test and let me know if there any issue, and I'll release a little later this week.

**Comment by potmat** [comment]
Works great!

**Comment by noahlz** [comment]
1.11.2 is released and available in Maven Central.
