### ISSUE TITLE
Grater has trouble dealing with List-s and Option-s that live next to eachother

### ISSUE THREAD

**Issue by manuelbernhardt** [salat/salat#24]
This happened to me a few times already: basically, whenever I have a case class with a collection member followed by an Option, I get a grater glitch on `wrong number of arguments`. For example (simplified):

    case class MetadataRecord(
      validOutputFormats: List[String] = List.empty[String], // valid formats this records can be mapped to
      transferIdx: Option[Int] = None, // 0-based index for the transfer order
      deleted: Boolean = false, // if the record has been deleted
    )

will not work, whilst

    case class MetadataRecord(
      validOutputFormats: List[String] = List.empty[String], // valid formats this records can be mapped to
      deleted: Boolean = false, // if the record has been deleted
      transferIdx: Option[Int] = None, // 0-based index for the transfer order
    )

does work.

**Comment by noahlz** [comment]
@manuelbernhardt I'm closing this old issue, which presumably was fixed in one of the releases of mongo driver and/or salat in the intervening 5 years. Please re-open if it is still an issue!
