### ISSUE TITLE
ClassCastExceptions using Play 2.0

### ISSUE THREAD

**Issue by mariussoutier** [salat/salat#32]
Hi,

we're constantly running into class cast exceptions when using hierarchies with Salat and Play 2.0.

The code looks like this:

```scala
@Salat
sealed abstract class EventLike(
  @Persist val _id: ObjectId
  //...
)

case class Event(override val _id: ObjectId = new ObjectId, ...) extends EventLike(_id = _id)
case class MiniEvent(override val _id: ObjectId = new ObjectId, ...) extends EventLike(_id = _id)

```

The error is:

`[ClassCastException: models.Event cannot be cast to models.EventLike]`

We're using a custom context, defined in a package object:

```scala
package object db {
  implicit val ctx = {
    import com.novus.salat._
    import play.api.Play
    import play.api.Play.current
    val c = new Context {
      val name = "play-salat-context"
    }
    c.registerClassLoader(Play.current.classloader)
    c
  }
}

```

This happens during development after making some changes, but can't be reproduced reliably.

**Comment by noahlz** [comment]
@mariussoutier and @leon both reported this fixed.

Closing unless @mariussoutier or a successor wants to re-open with new reproduction steps.
