### ISSUE TITLE
Cannot deserialize JSON to case class with Optional enum field.

### ISSUE THREAD

**Issue by mzafer** [salat/salat#55]
Hi Rose,

I ran into a error when deserializing a JSON string to a model that has enums. If I do not overwrite the enum strategy I get the below error

      [error] Not sure how to handle value='Some(mon)' as enum of class model.Weekday using strategy BY_VALUE

and if I overwrite the enum strategy to BY_ID I get the below error.

       [error] Not sure how to handle value='Some(1)' as enum of class model.Weekday using strategy BY_ID

I have updated my existing MongoDate github project that recreates these errors. To run the test ,get the latest and use the below commands

>test-only -- include testEnum 

The github project is at https://github.com/mzafer/MongoDate

Thanks
Zafer

**Comment by noahlz** [comment]
If I'm not mistaken, #129 resolved this?  Please re-open if I got that wrong.
