### ISSUE TITLE
evaluate if play-json could be used instead of current lib

### ISSUE THREAD

**Issue by leon** [salat/salat#77]
play 2.2 will have a separate lib for its json handling. if we where to change to use it in salat, this would mean that if you where using salat together with play it would be more seamless.

I'm not shure if this is a good idea but I thought id put it out there.

http://mandubian.com/2013/02/21/play-json-stand-alone/

**Comment by noahlz** [comment]
(Triaging old issues)

Given the state of the project (slowly getting it back under way, hesitant to do any major re-work), and that this is an old request - I don't think we will change from using json4s.
