### ISSUE TITLE
Defining Unique Indexes

### ISSUE THREAD

**Issue by DeaconDesperado** [salat/salat#93]
I'm familiar with the methods from the Scalathon presentation for defining unique indexes on collections:

https://github.com/rktoomey/scalathon-presentation/blob/master/src/main/scala/prasinous/Conf.scala

I'm curious, is this the recommended way to enforce the unique constraint on the persistency side?  Is there no way to define this from within the models themselves?  How does the SalatDAO handle attempted inserts that violate unique constraints internally?

**Comment by noahlz** [comment]
(Just seeing this now, sorry!)

SalatDAO does not have an API for defining unique constraints, other than what Mongo code you write yourself via Casbah, etc.  If you attempt an insert that violates a constraint, you will get an error (which your application should handle).
